eslint/csstree

.github/workflows/build.yml, lib/index.d.ts, package-lock.json, package.json, tests/types/tsconfig.json, tests/types/types.test.ts
This pull request introduces several changes to add TypeScript support and configuration for type checking in the project. The most important changes include adding a new job to the GitHub Actions workflow, updating `package.json` to include TypeScript dependencies and scripts, and creating TypeScript configuration and test files.
This uses https://gist.github.com/scripthunter7/3274e68ed223102246c098dcf1a772f0 as the basis for the types. It's not complete but covers most of the API.
Needs #1 before merging.
* [`.github/workflows/build.yml`](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R83-R96): Added a new job `test_types` to run TypeScript checks during the CI process.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6 …
=> feat: Add type definitions

lib/index.d.ts, tests/types/types.test.ts
Adds missing types for the newly-added `onToken` callback API and updated the types test to account for this API.
=> fix: Add types for onToken callback

lib/index.d.ts, tests/types/types.test.ts
The `parse` function actually has [two additional properties](https://github.com/eslint/csstree/blob/b403ffb6085d5e8c481f62026d88eebd632a3cb5/lib/parser/create.js#L384-L387):
1. `SyntaxError` - the error used for parsing errors internally
2. `config` - the config used to create the function
This PR adds types for these properties.
=> fix: Add parse.SyntaxError and parse.config types

lib/__tests/lexer-match-property.js, lib/lexer/Lexer.js
This pull request introduces changes to support typed custom properties in the lexer. The most important changes include adding a new typed custom property, updating the lexer to handle these properties, and adding tests to ensure the correct functionality.
Port of
https://github.com/csstree/csstree/pull/256
cc @romainmenke
Enhancements to lexer functionality:
* [`lib/lexer/Lexer.js`](diffhunk://#diff-629ab198b211be814fa3ac4242eb8cb58113284fbd3a775cc55bd18d4b6f0242L359-R362): Modified the `matchProperty` method to handle typed custom properties by checking if the property is not found and is a custom property.
Testing improvements:
* [`lib/__tests/lexer-match-property.js`](diffhunk://#diff-02ffb908de7190c5ace89f8cbe8ab28a8bec6b9f42f1aac2f1e33da4d8d34b06L12-R13): Added a new typed custom …
=> feat: Add support for typed custom properties

fixtures/definition-syntax/env.json, lib/__tests/lexer-match-property.js, lib/lexer/Lexer.js
This pull request includes changes to handle `env()` values in the lexer and improve error handling for unsupported syntax. The most important changes include adding a new function to detect `env()` values, updating the match syntax function to handle `env()` values, and adding test cases to ensure the new functionality works correctly.
Port of:
https://github.com/csstree/csstree/pull/245
cc @romainmenke
Enhancements to lexer functionality:
* [`lib/lexer/Lexer.js`](diffhunk://#diff-629ab198b211be814fa3ac4242eb8cb58113284fbd3a775cc55bd18d4b6f0242R66-R75): Added a new function `valueHasEnv` to detect `env()` values in tokens and updated the `matchSyntax` function to return an error when `env()` values are detected. [[1]](diffhunk://#diff-629ab198b211be814fa3ac4242eb8cb58113284fbd3a775cc55bd1 …
=> feat: passthrough env() in lexer syntax matching

lib/index.d.ts, tests/types/types.test.ts
It turned out we had two types essentially representing the same thing, so I merged them.
Also `parse.SyntaxError` actually isn't a constructor, just a function, so I updated that type definition as well.
=> fix: SyntaxParseError type

lib/index.d.ts, tests/types/types.test.ts
The `CssNodePlain` type was missing the `NestingSelector` entry, making it out of sync with `CssNode`. I added `NestingSelector` and some comments to remind people to always update these types at the same time.
I also added several missing node types:
- `Layer`, `LayerList`, and `LayerListPlain`
- `Condition` and `ConditionPlain`
- `Feature`, `FeatureFunction`, `FeatureFunctionPlain`, and `FeatureRange`
Additionally, I updated several method signatures to accept both `CssNode` and `CssNodePlain`.
**Help wanted:** I couldn't quite figure out how to add a test to ensure that everything in `CssNodeNames` matches `CssNode` and `CssNodePlain`.
=> fix: Add missing node types and update other types

data/patch.json
this patch is not correct: the spec's version and mdn-data's version is both `[ <'scroll-timeline-name'> <'scroll-timeline-axis'>? ]#`, while the patch's version is `[ <'scroll-timeline-name'> || <'scroll-timeline-axis'> ]#`
browsers implement as the spec defines
see https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-timeline and https://drafts.csswg.org/scroll-animations/#propdef-scroll-timeline
this mirrors https://github.com/csstree/csstree/pull/331
=> fix: Remove wrong `scroll-timeline` property patch

data/patch.json
Patches the missing `mdn-data` `<cubic-bezier-easing-function>`
fixes #27
=> fix: Add patch for <cubic-bezier-easing-function>

data/patch.json, fixtures/definition-syntax/default-properties.json
it is a descriptor of `@font-face` at-rule, not a CSS property; so it should not be patched here
this mirrors https://github.com/csstree/csstree/pull/330
=> fix: Remove `src` descriptor patch

data/patch.json
similar to `src` descriptor, it is also a descriptor of the `@font-face` at-rule; and the patch's syntax is outdated, too
see https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range
this mirrors https://github.com/csstree/csstree/pull/332
=> fix: Remove `unicode-range` descriptor patch

data/patch.json
the `<absolute-color-base>` and `<absolute-color-function>` syntaxes are never used anywhere, neither in mdn-data nor in csstree
also, these syntaxes are not in the https://www.w3.org/TR/css-color-4/#color-syntax reference, too (maybe they are removed from spec long ago)
this mirrors https://github.com/csstree/csstree/pull/335
=> chore: Remove never used syntaxes

data/patch.json
the spec has renamed `<anchor-element>` to `<anchor-name>`, and the syntax in csstree is outdated; the syntax in mdn-data is the latest which match the spec
see:
https://developer.mozilla.org/en-US/docs/Web/CSS/anchor
https://developer.mozilla.org/en-US/docs/Web/CSS/anchor-size
https://drafts.csswg.org/css-anchor-position-1/#funcdef-anchor
https://drafts.csswg.org/css-anchor-position-1/#funcdef-anchor-size
this mirrors https://github.com/csstree/csstree/pull/334
=> fix: Remove outdated `anchor()` & `anchor-size()` function patch

lib/index.d.ts, lib/syntax/node/CDC.js, lib/syntax/node/CDO.js, tests/types/types.test.ts
This fixes the types for node definitions, which were previously incorrect.
I used all of the files in https://github.com/eslint/csstree/tree/main/lib/syntax/node as examples and added type test for the `fork()` function to verify.
=> fix: Types for Node definitions

CHANGELOG.md, lib/__tests/common.js, lib/generator/create.js, lib/index.d.ts, lib/lexer/prepare-tokens.js, lib/parser/create.js, lib/syntax/config/mix.js, lib/syntax/config/parser.js, lib/syntax/create.js, lib/utils/get-tokenizer.js
Bring changes from https://github.com/csstree/csstree/pull/264
> This is a relatively simple PR that allows advanced library users to use a custom tokenizer via the fork API. This PR doesn't change how the base library works, it only affects the forks and makes them even more flexible.
> 
> Custom tokenizer function can be a completely new tokenizer or a simple wrapper around CSSTree's tokenizer, the point is that it should meet the following requirements:
> 
> 1. It should be compatible with the following signature:
>    ```ts
>    /**
>     * CSSTree's tokenizer signature
>     *
>     * @param source CSS source code to tokenize
>     * @param onToken Callback which will be invoked when a token is found
>     */
>    function tokenize(source: string, onToken: (tokenType: number, …
```
=> feat: Customize tokenizer via the fork API

.github/workflows/build.yml, tests/types/types.test.ts
This pull request updates the Node.js version and GitHub Actions dependencies in the `.github/workflows/build.yml` file to ensure compatibility and take advantage of the latest features and improvements.
Without this, all the CI jobs are failing.
**Workflow updates:**
* Updated `PRIMARY_NODEJS_VERSION` from 18 to 20 to use the latest stable Node.js version.
* Upgraded `actions/checkout` from version `v2` to `v4` across all jobs for improved performance and features. [[1]](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L8-R17) [[2]](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L31-R33) [[3]](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L63-R65)
* Upgraded `actions/setup-node` from …
=> ci: Update GitHub actions

lib/index.d.ts, tests/types/types.test.ts
I ran into some more incorrect types as I've been working on the CSS plugin. Specifically, the definition for `NodeSyntaxConfig` contained a couple of errors:
- `structure.children` - this needs to be a two-dimensional array of strings
- the `descriptors` property of at-rules is optional
=> fix: Types for NodeSyntaxConfig

data/patch.json
This was causing an error when I tried linting a personal project.
=> fix: Add missing <parenthesis-block> type

lib/data.d.ts, lib/index.d.ts, package.json, tests/types/types.test.ts
Continuing my mission to fix the CSSTree types:
1. Provide definitions for the `/definition-syntax-data` entrypoint
2. Fix the type for `loc` on nodes
3. Allow optional arguments in `NodeSyntaxConfig["parse"]` to align with how `parse` is used in the package.
=> fix: Types for default-syntax-data and nodes

lib/index.d.ts, tests/types/types.test.ts
I'm continuing to find incorrect types. This time, the objects passed into `fork()` can actually be partials, so I've updated the corresponding types and tests.
=> fix: Types for custom nodes and scopes

fixtures/ast/rule/nesting.json, lib/syntax/node/Block.js, lib/syntax/node/Rule.js
This adds support for parsing most nested element selectors:
```css
div {
a {}
a.foo {}
a[href] {}
a, b {}
a > b {}
a + b {}
}
```
The only pattern it doesn't currently cover is when a pseudoclass or pseudoelement is immediately attached to the element, like this:
```css
div {
a:hover {}
}
```
That's because `a:hover` looks like a property and I haven't yet figured out an efficient way to discover whether it's a property or a selector.
refs #33
=> feat: Parse nested element selector

lib/index.d.ts, tests/types/types.test.ts
The `this` value inside of a node's `parse()` method actually has methods for every registered node type, such as `this.Identifier()`, `this.Declaration()`, etc. It's common for one node's `parse()` method to call another, so including all of these methods by default improves the developer experience greatly.
I also added the ability to augment `ParserContext` with a custom list of nodes to allow for extensions to easily add new nodes and still have good type checking.
=> fix: ParserContext type to have all methods

data/patch.json, lib/__tests/lexer-relative-colors.js
Fix https://github.com/eslint/css/issues/235
Allow relative color syntax for rgb() and rgba(), following syntaxes are now valid:
```js
/* Relative values */
rgb(from green r g b / 0.5)
rgb(from #123456 calc(r + 40) calc(g + 40) b)
rgb(from hwb(120deg 10% 20%) r g calc(b + 200))
rgb(from hsl(0 100% 50%) r g b)
rgb(from hsl(0 100% 50% / 0.8) r g b / alpha)
rgb(from hsl(0 100% 50% / 0.8) r g b / 0.5)
rgb(from hsl(0 100% 50%) calc(r/2) calc(g + 25) calc(b + 175) / calc(alpha - 0.1))
```
=> fix: allow relative color syntax for rgb()
